config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'trainer_login' => 'advisor#login'
 

  resources :accounts

  devise_for :users
  devise_for :trainees, :skip => [:registrations, :sessions, :passwords]
  devise_for :trainers, :skip => [:registrations, :sessions, :passwords, :logins]	

root :to => "home#index"

match "/trainers/sign_in"  => "trainer#signIn", :via => [:get, :post]
match '/trainers/login'  => 'trainer#login', :via => [:get, :post]
match "/trainers/profil", :to => "trainer#profil", :via => [:get, :post]
match "/trainers/trainees", :to => "trainer#afficherTrainees", :via => [:get, :post]
match "/trainers/changepassword", :to => "trainer#changepassword", :via => [:get, :post]
match "/trainers/options", :to => "trainer#options", :via => [:get, :post]
match "/trainers/saveInvoice", :to => "trainer#saveInvoice", :via => [:get, :post]

match "/home/trainer"  => "home#trainer", :via => [:get, :post]
match "/home/trainee"  => "home#trainee", :via => [:get, :post]
match "/home/expandableRowTemplate"=> "home#expandableRowTemplate" , :via => [:get, :post]
match "/home/user"  => "home#user", :via => [:get, :post]
match '*any' => 'application#options', :via => [:options]
match "/home/option"  => "home#option", :via => [:get, :post]
match "/home/package"  => "home#package", :via => [:get, :post]
match "/home/savePackage"  => "home#savePackage", :via => [:get, :post]

    match "/trainee/trainee_edit_entry", :to => "trainee#trainee_edit_Entry", :via => [:get, :post]

    match "/trainers/register", :to => "trainer#registration", :via => [:get, :post]
    match "/trainers/sign_in", :to => "trainer#signIn", :via => [:get, :post]
    match "/trainers/sign_out", :to => "trainer#signOut", :via => [:get, :post]
    match "/trainers/template/create", :to => "trainer#create_template", :via => [:get, :post]
    match "/trainers/template/edit", :to => "trainer#edit_template", :via => [:get, :post]
    match "/trainer/delete_templates", :to => "template#delete_template", :via => [:get, :post]

    match "trainer/list_trainees_with_templates", :to => "trainer#list_trainees_with_templates_for_settings", :via => [:get, :post]
    match "trainer/assign_them_templates", :to => "trainer#assign_them_templates", :via => [:get, :post]
    match "trainer/list_selected_trainee_with_templates", :to => "trainer#list_selected_trainee_with_templates", :via => [:get, :post]
    match "trainer/assign_user_templates", :to => "trainer#assign_user_templates", :via => [:get, :post]

    match "/trainer/overall_feedback", :to => "trainer#overall_feedback", :via => [:get, :post]

    match "/trainers/update_loc", :to => "trainer#update_loc", :via => [:get, :post]

    match "/trainers/list_trainees", :to => "trainer#listTrainees", :via => [:get, :post]

    match "/trainee/delete_trainers", :to => "trainee#delete_trainers", :via => [:get, :post]

    match "/trainee/followed_trainers_and_templates_assigned", :to => "trainee#followed_trainers_and_templates_assigned", :via => [:get, :post]

    match "/trainee/set_profile_active", :to => "trainee#set_profile_active", :via => [:get, :post]

    match "/trainee/register", :to => "trainee#registration", :via => [:get, :post]
    match "/trainee/sign_in", :to => "trainee#signIn", :via => [:get, :post]
    match "/trainee/sign_out", :to => "trainee#signOut", :via => [:get, :post]
    match "/trainers/list", :to => "trainee#listAllTrainers", :via => [:get, :post]
    match "/trainers/followed", :to => "trainee#listFollowedTrainers", :via => [:get, :post]

    match "/trainer/home_year", :to => "trainer#home_year", :via => [:get, :post]
    match "/trainer/home_month", :to => "trainer#home_month", :via => [:get, :post]
    match "/trainer/home_day", :to => "trainer#home_day", :via => [:get, :post]
    match "/trainer/list_day_entries", :to => "trainer#list_day_entries", :via => [:get, :post]
    match "/trainer/which_screen_to_jump_to", :to => "trainer#which_screen_to_jump_to", :via => [:get, :post]

    match "/trainer/follow", :to => "trainee#followTrainer", :via => [:get, :post]
    match "/trainee/entry/create", :to => "trainee#create_entry", :via => [:get, :post]
    match "/entry/edit", :to => "trainee#edit_entry", :via => [:get, :post]

    match "/trainee/home_year", :to => "trainee#home_year", :via => [:get, :post]
    match "/trainee/home_month", :to => "trainee#home_month", :via => [:get, :post]
    match "/trainee/home_day", :to => "trainee#home_day", :via => [:get, :post]
    match "/trainee/list_day_entries", :to => "trainee#list_day_entries", :via => [:get, :post]
    match "/trainee/which_screen_to_jump_to", :to => "trainee#which_screen_to_jump_to", :via => [:get, :post]
    match "/trainee/share_entries_with_another_trainer", :to => "trainee#share_entries_with_another_trainer", :via => [:get, :post]
    match "/trainee/trainers_for_a_template", :to => "trainee#trainers_for_a_template", :via => [:get, :post]

    match "/trainee/refresh_blocked_items", :to => "trainee#refresh_blocked_items", :via => [:get, :post]

    match "/trainer/subscribe_to_template", :to => "trainer#subscribe_to_template", :via => [:get, :post]

    match "/template/show_all", :to => "template#show_all", :via => [:get, :post]
    match "/template/show", :to => "template#show", :via => [:get, :post]
    match "/template/show_entry", :to => "template#show_entry", :via => [:get, :post]

    match "/trainee/register_push", :to => "trainee#register_for_push", :via => [:get, :post]
    match "/trainer/register_push", :to => "trainer#register_for_push", :via => [:get, :post]

    match "/trainee/test_notif", :to => "trainee#test_notif", :via => [:get, :post]
    
    match "/trainee/search", :to => "trainee#trainee_search", :via => [:get, :post]
    match "/trainer/search", :to => "trainer#trainer_search", :via => [:get, :post]

    match "/trainer/week_graph_fbk", :to => "trainer#week_graph_fbk", :via => [:get, :post]
    match "/trainer/month_graph_fbk", :to => "trainer#month_graph_fbk", :via => [:get, :post]

    match "/trainee/week_graph_fbk", :to => "trainee#week_graph_fbk", :via => [:get, :post]
    match "/trainee/month_graph_fbk", :to => "trainee#month_graph_fbk", :via => [:get, :post]

    
    match "/trainer/forgot", :to => "resets#trainer_reset_password_token", :via => [:get, :post]
    match "/trainee/forgot", :to => "resets#trainee_reset_password_token", :via => [:get, :post]

    match "/trainer/reset_password", :to => "resets#trainer_change_password", :via => [:get, :post]
    match "/trainee/reset_password", :to => "resets#trainee_change_password", :via => [:get, :post]  

    match "/trainee/delete_entries", :to => "trainee#delete_entries", :via => [:get, :post] 

match "/functions/getallUsers", :to => "home#listAllUsers", :via => [:get, :post] 
match "/functions/getallTrainers", :to => "home#listAllTrainers", :via => [:get, :post] 
match "/functions/getallTrainees", :to => "home#listAllTrainees", :via => [:get, :post]
match "/functions/updateTrainer", :to => "home#updateTrainer", :via => [:get, :post]
match "/functions/getallPackages", :to => "home#listAllPackages", :via => [:get, :post]
match "/functions/getallDiscounts", :to => "home#listAllDiscounts", :via => [:get, :post]
match "/functions/updatePackage", :to => "home#updatePackage", :via => [:get, :post]
match "/functions/updateDiscount", :to => "home#updateDiscount", :via => [:get, :post]
match "/trainers/getallTraineesTrainer", :to => "trainer#listAllTrainees", :via => [:get, :post]

end

app/controllers/advisor_controller.rb
class AdvisorController < ApplicationController
	require "#{Rails.root}/lib/token_generator"
	before_filter :trainer_token_authentication

	skip_before_action :verify_authenticity_token

	def login
		@trainer = Trainer.new
	end
	
	def profil
		render layout: "pagecompleteTrainer"
	end

end

app/views/advisor/forgot_password.html.erb
<h2>Forgot your password?</h2>

<%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, autofocus: true %></div>

  <div><%= f.submit "Send me reset password instructions" %></div>
<% end %>

<%= render "devise/shared/links" %>

app/views/advisor/profil.html.erb
<html>
<head>
	<title>BlueWave</title>
</head>
<body>
<div>

<div class="border-form-div">
	<%= image_tag("blue_wave.jpg", :alt => "rss feed", :class => "imgSign")%>
  	<h2>Adviser Registration</h2>
  	<form accept-charset="UTF-8" action="trainer_registration" class="new_user" id="registration_form">
		<input autofocus="autofocus" name="trainer[f_name]" id="f_name" placeholder="First name" type="text" required >
	<input autofocus="autofocus" name="trainer[l_name]" id="l_name" placeholder="Last name" type="text" required >
    		<input autofocus="autofocus" id="email" name="trainer[email]" placeholder="Email address" type="email" ng-model="email" required >
    		<input id="password" name="trainer[password]" placeholder="Password" type="password" ng-model='password' required >
		<input name="page" type="hidden" value="1">
    		<input id="encrypted_password" name="trainer[encrypted_password]" placeholder="Password" type="password" ng-model='password' required >
		<select autofocus="autofocus" name="package" id="package" type="select">
			  <option value="1">Trial Adivisor</option>
			  <option value="2">Junior Advisor</option>
			  <option value="3">Senior Advisor</option>
			  <option value="4">Unlimited Advisor</option>
		</select>
          
<div class="form-control-group">
            
            <div class="controls">
             <input id="agree" class="checkbox" type="checkbox" name="agree" required >
	     <label class="control-label" for="message"> 12 month pre-paid subscription</label>
            </div>
          </div>
    		<input class="btn btn-primary" name="commit" type="submit" value="Sign up" ng-click="submit($event)">
	</form>    
	<a href="trainer_login">Sign in</a><br>
</div>
</div>
</body>
</html>

app/views/advisor/registration.html.erb
okokokoko

app/views/advisor/signIn.html.erb
okokokoko